### ISSUE TITLE
Add the ability to automatically infer block durations

### ISSUE THREAD

**Issue by RobScheidegger** [USC-ACTLab/MultiRobotArt#10]
Should have a way to automatically infer the duration of user generated blocks. Hypothetical way to do this:

1. Make the simulator commands have a mode where they don't actually execute, but just keep track of the amount of time that _would_ have been used to execute a command.
2. Have this run on block save (should be inexpensive), and update the block that way.

Also would need a way to manually override this in case of strange/complicated blocks.

**Comment by ewinge1** [comment]
(and then stretch a block to the proper duration with #9)
