### ISSUE TITLE
Add (basic) collision detection in simulation

### ISSUE THREAD

**Issue by RobScheidegger** [USC-ACTLab/MultiRobotArt#15]
Use ellipses around robots to check basic collisions (need to determine bounds).

Add a warning that robots may behave differently when actually running because they will try to avoid collisions automatically.

Should probably just make them red if there is an intersection.

**Comment by Hammad-Izhar** [comment]
#30 implements some, but not all of these features

a) uses rectangular prisms instead of ellipses
b) no working, but should be a simple toast to add later
