### ISSUE TITLE
wireframes aren't always visible

### ISSUE THREAD

**Issue by Hammad-Izhar** [USC-ACTLab/MultiRobotArt#33]
this probably is an issue with when the crazyflie component is re-rendered.

**Comment by Hammad-Izhar** [comment]
also it seems there might be a bug when the robots are first loaded in since without a reload of the simulation (via saving in vscode) everything seems to collide with everything else.

**Comment by ewinge1** [comment]
Should be solved by [e145606](https://github.com/USC-ACTLab/MultiRobotArt/commit/e145606b1dc5bebf4c5404aed73a0c1e3d1e3f5e)
