### ISSUE TITLE
Fix axes in simulator

### ISSUE THREAD

**Issue by RobScheidegger** [USC-ACTLab/MultiRobotArt#8]
Currently, the `y` direction is up because computer graphics people are cringe. We need to fix this in the actual coordinate system and the axis helper.

**Comment by ewinge1** [comment]
So Z now points up... only because the y axis is labeled Z and the Z axis is labeled y. Will certainly not cause any confusion in the future... The y axis points in the wrong direction (towards you, not away from you), which is annoying, but whatever.
